import Foundation
import LocalisModels

/// Marker host id for a session the store cannot attribute to a machine.
///
/// `Session.hostID` is non-optional because a conversation belongs to exactly
/// one machine for life (FR-030). But the store holds one shape that predates
/// that rule: rows written before Amendment A, which carry no machine at all.
/// When migration cannot attribute them with certainty — zero paired hosts, or
/// several — FR-038 says to keep them readable rather than guess or delete.
///
/// Such a row is projected with this id and `status == .orphaned`, which makes
/// it browsable and, because `canSend` is false for `.orphaned`, unsendable. The
/// alternative shapes were worse: hiding the rows loses conversations in the UI,
/// and guessing a machine files them under the wrong one silently.
///
/// The invariant, asserted in `UnattributedHostTests`: a session carrying this
/// id is always `.orphaned`, and no session on a real machine ever carries it.
extension HostID {
    /// Reserved all-zero id. Never generated by pairing, which uses `UUID()`.
    public static let unattributed = HostID(
        rawValue: UUID(uuidString: "00000000-0000-0000-0000-000000000000")!
    )

    /// Whether this id marks a session with no known machine.
    public var isUnattributed: Bool { self == .unattributed }
}
